using Accounting.Data;
using Accounting.Models.DTOs;
using Accounting.Models.DTOs.Loan;
using Accounting.Models.Entities;
using Accounting.Models.Enums;
using Accounting.Services.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Accounting.Services.Implementations;

public class LoanService : ILoanService
{
    private readonly AccountingDbContext _db;

    public LoanService(AccountingDbContext db)
    {
        _db = db;
    }

    public async Task<LoanResponse> CreateAsync(Guid companyId, CreateLoanRequest request)
    {
        var loanPrefix = "LOAN-";
        var maxLoanNum = await _db.Loans
            .IgnoreQueryFilters()
            .Where(l => l.CompanyId == companyId && l.LoanNumber.StartsWith(loanPrefix))
            .Select(l => l.LoanNumber)
            .MaxAsync() as string;
        var loanSeq = 1;
        if (maxLoanNum != null)
        {
            var lastPart = maxLoanNum.Substring(loanPrefix.Length);
            if (int.TryParse(lastPart, out var parsed)) loanSeq = parsed + 1;
        }
        var loanNumber = $"{loanPrefix}{loanSeq:D6}";

        // Calculate monthly payment using standard amortization formula
        // PMT = P * [r(1+r)^n] / [(1+r)^n - 1]
        var monthlyPayment = CalculateMonthlyPayment(
            request.PrincipalAmount,
            request.InterestRate,
            request.TermMonths,
            request.InterestType);

        var maturityDate = request.FirstPaymentDate.AddMonths(request.TermMonths - 1);

        var loan = new Loan
        {
            CompanyId = companyId,
            LoanNumber = loanNumber,
            LoanType = request.LoanType,
            Name = request.Name,
            Lender = request.Lender,
            ContactId = request.ContactId,
            PrincipalAmount = request.PrincipalAmount,
            InterestRate = request.InterestRate,
            InterestType = request.InterestType,
            TermMonths = request.TermMonths,
            DisbursementDate = request.DisbursementDate,
            FirstPaymentDate = request.FirstPaymentDate,
            MaturityDate = maturityDate,
            RepaymentFrequency = request.RepaymentFrequency,
            MonthlyPayment = monthlyPayment,
            OutstandingPrincipal = request.PrincipalAmount,
            LoanAccountId = request.LoanAccountId,
            InterestExpenseAccountId = request.InterestExpenseAccountId,
            BankAccountId = request.BankAccountId,
            Status = "Active"
        };

        _db.Loans.Add(loan);

        // Create journal entry for loan disbursement: Dr Cash/Bank, Cr Loan Payable
        if (loan.LoanAccountId.HasValue && loan.BankAccountId.HasValue)
        {
            var disbYm = DateTime.UtcNow.ToString("yyyyMM");
            var disbPrefix = $"LD-{disbYm}-";
            var maxDisbNum = await _db.JournalEntries
                .IgnoreQueryFilters()
                .Where(j => j.CompanyId == companyId && j.EntryNumber.StartsWith(disbPrefix))
                .Select(j => j.EntryNumber)
                .MaxAsync() as string;
            var disbSeq = 1;
            if (maxDisbNum != null)
            {
                var lp = maxDisbNum.Substring(disbPrefix.Length);
                if (int.TryParse(lp, out var parsed)) disbSeq = parsed + 1;
            }

            var disbEntry = new JournalEntry
            {
                CompanyId = companyId,
                EntryNumber = $"{disbPrefix}{disbSeq:D4}",
                EntryDate = request.DisbursementDate,
                Description = $"รับเงินกู้ {loanNumber} - {request.Name}",
                TotalDebit = request.PrincipalAmount,
                TotalCredit = request.PrincipalAmount,
                Status = JournalEntryStatus.Posted,
                IsAutoGenerated = true
            };

            disbEntry.Lines.Add(new JournalEntryLine
            {
                AccountId = loan.BankAccountId.Value,
                DebitAmount = request.PrincipalAmount,
                CreditAmount = 0,
                Description = "รับเงินกู้เข้าธนาคาร",
                LineOrder = 1
            });
            disbEntry.Lines.Add(new JournalEntryLine
            {
                AccountId = loan.LoanAccountId.Value,
                DebitAmount = 0,
                CreditAmount = request.PrincipalAmount,
                Description = "เจ้าหนี้เงินกู้",
                LineOrder = 2
            });

            _db.JournalEntries.Add(disbEntry);
        }

        await _db.SaveChangesAsync();

        return MapToResponse(loan);
    }

    public async Task<LoanResponse> GetByIdAsync(Guid companyId, Guid loanId)
    {
        var loan = await _db.Loans
            .FirstOrDefaultAsync(l => l.Id == loanId && l.CompanyId == companyId)
            ?? throw new KeyNotFoundException("ไม่พบข้อมูลสินเชื่อ");
        return MapToResponse(loan);
    }

    public async Task<PagedResponse<LoanResponse>> GetAllAsync(Guid companyId, string? status, PagedRequest request)
    {
        var query = _db.Loans.Where(l => l.CompanyId == companyId);

        if (!string.IsNullOrEmpty(status))
            query = query.Where(l => l.Status == status);

        if (!string.IsNullOrEmpty(request.Search))
        {
            var search = $"%{request.Search}%";
            query = query.Where(l => EF.Functions.ILike(l.LoanNumber, search) || EF.Functions.ILike(l.Name, search));
        }

        var totalCount = await query.CountAsync();

        var items = await query
            .OrderByDescending(l => l.CreatedAt)
            .Skip((request.Page - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync();

        var totalPages = (int)Math.Ceiling(totalCount / (double)request.PageSize);

        return new PagedResponse<LoanResponse>(
            items.Select(MapToResponse).ToList(),
            totalCount,
            request.Page,
            request.PageSize,
            totalPages);
    }

    public async Task<LoanResponse> UpdateAsync(Guid companyId, Guid loanId, UpdateLoanRequest request)
    {
        var loan = await _db.Loans
            .FirstOrDefaultAsync(l => l.Id == loanId && l.CompanyId == companyId)
            ?? throw new KeyNotFoundException("ไม่พบข้อมูลสินเชื่อ");

        if (request.Name != null) loan.Name = request.Name;
        if (request.Status != null) loan.Status = request.Status;

        if (request.InterestRate.HasValue)
        {
            loan.InterestRate = request.InterestRate.Value;
            // Recalculate monthly payment based on outstanding principal and remaining months
            var paidInstallments = await _db.LoanPayments
                .CountAsync(p => p.LoanId == loanId);
            var remainingMonths = Math.Max(1, loan.TermMonths - paidInstallments);
            loan.MonthlyPayment = CalculateMonthlyPayment(
                loan.OutstandingPrincipal,
                request.InterestRate.Value,
                remainingMonths,
                loan.InterestType);
        }

        await _db.SaveChangesAsync();
        return MapToResponse(loan);
    }

    public async Task<List<LoanScheduleResponse>> GenerateScheduleAsync(Guid companyId, Guid loanId)
    {
        var loan = await _db.Loans
            .FirstOrDefaultAsync(l => l.Id == loanId && l.CompanyId == companyId)
            ?? throw new KeyNotFoundException("ไม่พบข้อมูลสินเชื่อ");

        // Remove existing unpaid schedules
        var existingSchedules = await _db.LoanSchedules
            .Where(s => s.LoanId == loanId && !s.IsPaid)
            .ToListAsync();
        _db.LoanSchedules.RemoveRange(existingSchedules);

        var schedules = new List<LoanSchedule>();
        var balance = loan.PrincipalAmount;
        var monthlyRate = loan.InterestRate / 100m / 12m;
        var monthlyPayment = loan.MonthlyPayment;

        for (int i = 1; i <= loan.TermMonths; i++)
        {
            decimal interestPortion;
            decimal principalPortion;

            if (loan.InterestType == "FlatRate")
            {
                // Flat rate: interest is constant each period
                interestPortion = loan.PrincipalAmount * monthlyRate;
                principalPortion = loan.PrincipalAmount / loan.TermMonths;
                monthlyPayment = principalPortion + interestPortion;
            }
            else
            {
                // Standard amortization (Fixed/Floating)
                interestPortion = balance * monthlyRate;
                principalPortion = monthlyPayment - interestPortion;
            }

            // Last installment adjustment to handle rounding
            if (i == loan.TermMonths)
            {
                principalPortion = balance;
                monthlyPayment = principalPortion + interestPortion;
            }

            balance -= principalPortion;
            if (balance < 0) balance = 0;

            var schedule = new LoanSchedule
            {
                CompanyId = companyId,
                LoanId = loanId,
                InstallmentNumber = i,
                DueDate = loan.FirstPaymentDate.AddMonths(i - 1),
                PaymentAmount = Math.Round(monthlyPayment, 2, MidpointRounding.AwayFromZero),
                PrincipalPortion = Math.Round(principalPortion, 2, MidpointRounding.AwayFromZero),
                InterestPortion = Math.Round(interestPortion, 2, MidpointRounding.AwayFromZero),
                RemainingBalance = Math.Round(balance, 2, MidpointRounding.AwayFromZero)
            };

            schedules.Add(schedule);
        }

        _db.LoanSchedules.AddRange(schedules);
        await _db.SaveChangesAsync();

        return schedules.Select(MapScheduleToResponse).ToList();
    }

    public async Task<List<LoanScheduleResponse>> GetScheduleAsync(Guid companyId, Guid loanId)
    {
        var schedules = await _db.LoanSchedules
            .Where(s => s.LoanId == loanId && s.CompanyId == companyId)
            .OrderBy(s => s.InstallmentNumber)
            .ToListAsync();

        return schedules.Select(MapScheduleToResponse).ToList();
    }

    public async Task<LoanPaymentResponse> MakePaymentAsync(Guid companyId, Guid loanId, MakeLoanPaymentRequest request, string performedBy)
    {
        var loan = await _db.Loans
            .FirstOrDefaultAsync(l => l.Id == loanId && l.CompanyId == companyId)
            ?? throw new KeyNotFoundException("ไม่พบข้อมูลสินเชื่อ");

        if (loan.Status != "Active")
            throw new InvalidOperationException("สินเชื่อไม่อยู่ในสถานะใช้งาน");

        // Mark schedule as paid
        var schedule = await _db.LoanSchedules
            .FirstOrDefaultAsync(s => s.LoanId == loanId && s.InstallmentNumber == request.InstallmentNumber);
        if (schedule != null)
        {
            schedule.IsPaid = true;
            schedule.PaidDate = request.PaymentDate;
        }

        var totalPaid = request.PrincipalPaid + request.InterestPaid + (request.LateFee ?? 0);

        var payment = new LoanPayment
        {
            CompanyId = companyId,
            LoanId = loanId,
            InstallmentNumber = request.InstallmentNumber,
            PaymentDate = request.PaymentDate,
            PrincipalPaid = request.PrincipalPaid,
            InterestPaid = request.InterestPaid,
            TotalPaid = totalPaid,
            LateFee = request.LateFee,
            PaymentMethod = request.PaymentMethod,
            Reference = request.Reference,
            CreatedBy = performedBy
        };

        _db.LoanPayments.Add(payment);

        // Update loan balances
        loan.OutstandingPrincipal -= request.PrincipalPaid;
        loan.TotalPrincipalPaid += request.PrincipalPaid;
        loan.TotalInterestPaid += request.InterestPaid;

        if (loan.OutstandingPrincipal <= 0)
        {
            loan.OutstandingPrincipal = 0;
            loan.Status = "PaidOff";
        }

        // Create journal entry for loan payment
        var lpYm = DateTime.UtcNow.ToString("yyyyMM");
        var lpPrefix = $"LP-{lpYm}-";
        var maxLpNum = await _db.JournalEntries
            .IgnoreQueryFilters()
            .Where(j => j.CompanyId == companyId && j.EntryNumber.StartsWith(lpPrefix))
            .Select(j => j.EntryNumber)
            .MaxAsync() as string;
        var lpSeq = 1;
        if (maxLpNum != null)
        {
            var lp = maxLpNum.Substring(lpPrefix.Length);
            if (int.TryParse(lp, out var parsed)) lpSeq = parsed + 1;
        }
        var journalEntry = new JournalEntry
        {
            CompanyId = companyId,
            EntryNumber = $"{lpPrefix}{lpSeq:D4}",
            EntryDate = request.PaymentDate,
            Description = $"ชำระสินเชื่อ {loan.LoanNumber} งวดที่ {request.InstallmentNumber}",
            TotalDebit = totalPaid,
            TotalCredit = totalPaid,
            Status = JournalEntryStatus.Posted,
            IsAutoGenerated = true
        };

        // Debit: Loan Account (reduce liability) + Interest Expense
        var lines = new List<JournalEntryLine>();
        if (loan.LoanAccountId.HasValue)
        {
            lines.Add(new JournalEntryLine
            {
                JournalEntryId = journalEntry.Id,
                AccountId = loan.LoanAccountId.Value,
                DebitAmount = request.PrincipalPaid,
                CreditAmount = 0,
                Description = "ชำระเงินต้น",
                LineOrder = 1
            });
        }
        if (loan.InterestExpenseAccountId.HasValue && request.InterestPaid > 0)
        {
            lines.Add(new JournalEntryLine
            {
                JournalEntryId = journalEntry.Id,
                AccountId = loan.InterestExpenseAccountId.Value,
                DebitAmount = request.InterestPaid,
                CreditAmount = 0,
                Description = "ดอกเบี้ยจ่าย",
                LineOrder = 2
            });
        }

        // Credit: Cash/Bank (total payment)
        var cashAccount = await _db.ChartOfAccounts.FirstOrDefaultAsync(a =>
            a.CompanyId == companyId && a.AccountCode == "11122" && a.Level >= 4)
            ?? await _db.ChartOfAccounts.FirstOrDefaultAsync(a =>
            a.CompanyId == companyId && a.AccountCode.StartsWith("111") && a.Level >= 4);
        if (cashAccount != null)
        {
            lines.Add(new JournalEntryLine
            {
                JournalEntryId = journalEntry.Id,
                AccountId = cashAccount.Id,
                DebitAmount = 0,
                CreditAmount = totalPaid,
                Description = $"จ่ายชำระสินเชื่อ {loan.LoanNumber}",
                LineOrder = 3
            });
        }

        journalEntry.Lines = lines;
        _db.JournalEntries.Add(journalEntry);
        payment.JournalEntryId = journalEntry.Id;

        await _db.SaveChangesAsync();

        return new LoanPaymentResponse(
            payment.Id, payment.InstallmentNumber, payment.PaymentDate,
            payment.PrincipalPaid, payment.InterestPaid, payment.TotalPaid,
            payment.LateFee, payment.PaymentMethod);
    }

    public async Task<List<LoanPaymentResponse>> GetPaymentsAsync(Guid companyId, Guid loanId)
    {
        var payments = await _db.LoanPayments
            .Where(p => p.LoanId == loanId && p.CompanyId == companyId)
            .OrderBy(p => p.InstallmentNumber)
            .ToListAsync();

        return payments.Select(p => new LoanPaymentResponse(
            p.Id, p.InstallmentNumber, p.PaymentDate,
            p.PrincipalPaid, p.InterestPaid, p.TotalPaid,
            p.LateFee, p.PaymentMethod)).ToList();
    }

    public async Task<LoanSummaryResponse> GetSummaryAsync(Guid companyId)
    {
        var loans = await _db.Loans
            .Where(l => l.CompanyId == companyId)
            .ToListAsync();

        var activeLoans = loans.Where(l => l.Status == "Active").ToList();
        var startOfYear = new DateTime(DateTime.UtcNow.Year, 1, 1);

        var interestPaidYTD = await _db.LoanPayments
            .Where(p => p.CompanyId == companyId && p.PaymentDate >= startOfYear)
            .SumAsync(p => p.InterestPaid);

        return new LoanSummaryResponse(
            TotalLoans: loans.Count,
            ActiveLoans: activeLoans.Count,
            TotalOutstandingPrincipal: activeLoans.Sum(l => l.OutstandingPrincipal),
            TotalMonthlyPayment: activeLoans.Sum(l => l.MonthlyPayment),
            TotalInterestPaidYTD: interestPaidYTD,
            Loans: loans.Select(MapToResponse).ToList());
    }

    // ===== Amortization Calculation =====

    /// <summary>
    /// Calculate monthly payment using standard amortization formula:
    /// PMT = P * [r(1+r)^n] / [(1+r)^n - 1]
    /// where P = principal, r = monthly rate, n = number of months
    /// </summary>
    private static decimal CalculateMonthlyPayment(decimal principal, decimal annualRate, int termMonths, string interestType)
    {
        if (principal <= 0 || termMonths <= 0)
            return 0;

        if (annualRate <= 0)
            return principal / termMonths;

        var monthlyRate = annualRate / 100m / 12m;

        if (interestType == "FlatRate")
        {
            // Flat rate: total interest = P * r * n, spread evenly
            var totalInterest = principal * monthlyRate * termMonths;
            return (principal + totalInterest) / termMonths;
        }

        // Standard amortization formula: PMT = P * [r(1+r)^n] / [(1+r)^n - 1]
        var rateDouble = (double)monthlyRate;
        var power = Math.Pow(1 + rateDouble, termMonths);
        var pmt = (double)principal * (rateDouble * power) / (power - 1);

        return Math.Round((decimal)pmt, 2, MidpointRounding.AwayFromZero);
    }

    // ===== Mappers =====

    private static LoanResponse MapToResponse(Loan l) => new(
        l.Id, l.LoanNumber, l.LoanType, l.Name, l.Lender,
        l.PrincipalAmount, l.InterestRate, l.InterestType, l.TermMonths,
        l.DisbursementDate, l.MaturityDate, l.MonthlyPayment,
        l.OutstandingPrincipal, l.TotalInterestPaid, l.Status, l.CreatedAt);

    private static LoanScheduleResponse MapScheduleToResponse(LoanSchedule s) => new(
        s.InstallmentNumber, s.DueDate, s.PaymentAmount,
        s.PrincipalPortion, s.InterestPortion, s.RemainingBalance,
        s.IsPaid, s.PaidDate);
}
