using Accounting.Models.Enums;

namespace Accounting.Models.Entities;

// ============================================================
// Period closing + year-end + opening balances + data migration
// — supports the Thai-RD-compliance ERP upgrade (Task 1 + Task 4
//   schema additions). Entities are TenantEntity so per-company
//   query filters apply.
// ============================================================

/// <summary>
/// Per-period opening balance per account. Generated by the year-end
/// close (carries forward Assets/Liabilities/Equity) or seeded
/// manually via the migration wizard. The trial balance sums these
/// alongside in-period postings for the "Opening | Debit | Credit |
/// Ending" report shape.
/// </summary>
public class OpeningBalance : TenantEntity
{
    public Guid FiscalPeriodId { get; set; }
    public FiscalPeriod FiscalPeriod { get; set; } = null!;

    public Guid AccountId { get; set; }
    public ChartOfAccount Account { get; set; } = null!;

    public decimal OpeningDebit { get; set; }
    public decimal OpeningCredit { get; set; }

    /// <summary>Optional cost-center allocation when the company uses
    /// dimensional accounting on opening balances.</summary>
    public Guid? DimensionId { get; set; }

    public string? Notes { get; set; }
}

/// <summary>
/// Audit row for a year-end closing operation. One row per closed
/// fiscal year — captures the net P&amp;L that was moved into Retained
/// Earnings and the journal entry that did the moving.
/// </summary>
public class YearEndClosing : TenantEntity
{
    public int FiscalYear { get; set; }

    /// <summary>The RE account credited (debited if loss) during the close.</summary>
    public Guid RetainedEarningsAccountId { get; set; }
    public ChartOfAccount RetainedEarningsAccount { get; set; } = null!;

    /// <summary>Net income (positive) or loss (negative) transferred.</summary>
    public decimal TransferredAmount { get; set; }

    /// <summary>The auto-generated journal entry that performs the transfer
    /// (Dr each revenue/expense to zero, Cr/Dr RE for the net).</summary>
    public Guid ClosingJournalEntryId { get; set; }
    public JournalEntry ClosingJournalEntry { get; set; } = null!;

    /// <summary>Locks every fiscal period in the closed year.</summary>
    public bool LockedFiscalPeriods { get; set; } = true;
}

/// <summary>
/// Migration session — tracks one COA/Trial-Balance/Sub-ledger import
/// from a legacy system. The wizard lets the user map legacy account
/// codes, upload TB + sub-ledgers, validate sub-totals against control
/// accounts, then commit. Status tracks the multi-step flow.
/// </summary>
public class MigrationSession : TenantEntity
{
    public string SessionName { get; set; } = null!;
    public MigrationType MigrationType { get; set; }
    public MigrationStatus Status { get; set; } = MigrationStatus.Draft;

    /// <summary>Fiscal period this migration seeds opening balances into.</summary>
    public Guid? TargetFiscalPeriodId { get; set; }

    /// <summary>Raw JSON of the mapping decisions (legacyCode → accountId,
    /// plus per-row notes). Kept as text for easy audit replay.</summary>
    public string? MappingsJson { get; set; }

    /// <summary>Summary written at commit time — totals imported,
    /// rows skipped, validation flags. Helps audit "what did we
    /// migrate?" months later.</summary>
    public string? ImportSummaryJson { get; set; }

    public DateTime? CompletedAt { get; set; }
    public string? CompletedBy { get; set; }
}

/// <summary>Per-row mapping inside a MigrationSession — legacy account
/// code/name from the source system, mapped to a current ChartOfAccount.
/// Used by COA Mapper UI and replayable on subsequent imports.</summary>
public class AccountMapping : BaseEntity
{
    public Guid MigrationSessionId { get; set; }
    public MigrationSession MigrationSession { get; set; } = null!;

    public string LegacyCode { get; set; } = null!;
    public string? LegacyName { get; set; }

    /// <summary>Null when the operator hasn't mapped this legacy account yet.</summary>
    public Guid? MappedAccountId { get; set; }
    public ChartOfAccount? MappedAccount { get; set; }

    /// <summary>Pre-import balance from the legacy file — validated
    /// against sub-ledger details at commit time.</summary>
    public decimal LegacyDebit { get; set; }
    public decimal LegacyCredit { get; set; }
}

// ============================================================
// Tax extensions — Task 4
// ============================================================

/// <summary>
/// Input-VAT deferral row. Thai law allows carrying Input VAT
/// forward up to 6 months when the related Tax Invoice arrives late.
/// One row per (document, deferred-to month) — the original tax
/// report keeps the document hidden from "claimable now", the
/// target report picks it up when the deferral month lands.
/// </summary>
public class VatDeferral : TenantEntity
{
    public Guid DocumentId { get; set; }
    public Document Document { get; set; } = null!;

    /// <summary>Original report this Input VAT would have landed in.</summary>
    public Guid OriginalTaxReportId { get; set; }
    public TaxReport OriginalTaxReport { get; set; } = null!;

    public decimal DeferredAmount { get; set; }
    public string? DeferralReason { get; set; }

    /// <summary>Source period (YYYY-MM int e.g. 202601 for Jan 2026).</summary>
    public int DeferredFromPeriod { get; set; }
    /// <summary>Target period to claim in — must be within 6 months by law.</summary>
    public int DeferredToPeriod { get; set; }

    /// <summary>Set once the target tax report has claimed the VAT.</summary>
    public DateTime? ClaimedAt { get; set; }
    public Guid? ClaimedTaxReportId { get; set; }
}

/// <summary>
/// E-Filing export artifact — one row per generated file. Captures
/// the pipe-delimited content the RD portal accepts, the period it
/// covers, and an audit timestamp so an operator can re-download or
/// re-verify what was filed.
/// </summary>
public class EFilingExport : TenantEntity
{
    /// <summary>Logical form code — PND.1 / PND.3 / PND.53 / PND.54 /
    /// PP.30 / PP.36.</summary>
    public string FormType { get; set; } = null!;

    public int PeriodYear { get; set; }
    public int PeriodMonth { get; set; }

    /// <summary>Pipe-delimited body content as required by RD e-Filing.</summary>
    public string FileContent { get; set; } = null!;

    public int LineCount { get; set; }
    public decimal TotalAmount { get; set; }
    public decimal TotalTax { get; set; }

    /// <summary>Optional reference number returned by RD after upload.</summary>
    public string? RdReferenceNumber { get; set; }

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    public string? GeneratedBy { get; set; }
}

// ============================================================
// OCR compliance logging — Task 5
// ============================================================

/// <summary>One row per RD-compliance check we run on a Document
/// after OCR extracts its fields. Used both as an audit trail and
/// as the source of "OcrValidationLog" UI badges.</summary>
public class OcrValidationLog : TenantEntity
{
    public Guid DocumentId { get; set; }
    public Document Document { get; set; } = null!;

    /// <summary>e.g. "TAX_INVOICE_KEYWORD", "SELLER_TAX_ID_FORMAT",
    /// "BRANCH_CODE_MISSING", "VAT_BREAKDOWN_MISMATCH",
    /// "TENANT_BUYER_MISMATCH".</summary>
    public string RuleCode { get; set; } = null!;

    public bool IsValid { get; set; }

    /// <summary>"Error" blocks acceptance, "Warning" surfaces but
    /// allows override, "Info" is purely informational.</summary>
    public string Severity { get; set; } = "Warning";

    public string? Message { get; set; }
    public string? FieldValue { get; set; }

    public Guid? OverriddenBy { get; set; }
    public DateTime? OverriddenAt { get; set; }
    public string? OverrideReason { get; set; }
}
