using Accounting.Models.Enums;

namespace Accounting.Models.Entities;

/// <summary>
/// General Ledger / Journal Entry
/// </summary>
public class JournalEntry : TenantEntity
{
    public string EntryNumber { get; set; } = null!;   // running number
    public DateTime EntryDate { get; set; }
    public JournalType JournalType { get; set; } = JournalType.General;  // ประเภทสมุดรายวัน
    public string? Description { get; set; }
    public string? Reference { get; set; }             // เลขอ้างอิง
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;
    public Guid? FiscalPeriodId { get; set; }
    public FiscalPeriod? FiscalPeriod { get; set; }
    public bool IsAutoGenerated { get; set; } = false;  // สร้างอัตโนมัติจากเอกสาร
    public Guid? SourceDocumentId { get; set; }         // อ้างอิงเอกสารต้นทาง
    public Guid? ReversedByEntryId { get; set; }        // รายการกลับรายการที่สร้างจากรายการนี้
    public Guid? OriginalEntryId { get; set; }          // รายการต้นทางที่ถูกกลับรายการ

    // Project / Branch / Cost Center allocation (header-level default)
    public Guid? ProjectId { get; set; }
    public Project? Project { get; set; }
    public Guid? BranchId { get; set; }
    public Guid? DimensionId { get; set; }              // Cost center / department

    // Free-form metadata
    public string? Note { get; set; }                   // หมายเหตุเพิ่มเติม
    public string? Tags { get; set; }                   // CSV tags e.g. "audit,external,2026Q1"

    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }

    // Navigation
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}

/// <summary>
/// รายการย่อยในใบสำคัญ (Debit/Credit lines)
/// </summary>
public class JournalEntryLine : BaseEntity
{
    public Guid JournalEntryId { get; set; }
    public JournalEntry JournalEntry { get; set; } = null!;
    public Guid AccountId { get; set; }
    public ChartOfAccount Account { get; set; } = null!;

    public decimal DebitAmount { get; set; }
    public decimal CreditAmount { get; set; }
    public string? Description { get; set; }
    public int LineOrder { get; set; }

    // Optional per-line allocation - falls back to header values when null
    public Guid? ProjectId { get; set; }
    public Project? Project { get; set; }
    public Guid? BranchId { get; set; }
    public Guid? DimensionId { get; set; }
    public string? Tags { get; set; }
}

/// <summary>
/// งวดบัญชี (Fiscal Period)
/// </summary>
public class FiscalPeriod : TenantEntity
{
    public string Name { get; set; } = null!;          // e.g. "2567/01"
    public int Year { get; set; }
    public int Month { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public FiscalPeriodStatus Status { get; set; } = FiscalPeriodStatus.Open;

    public ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();
}
