using Accounting.Models.Enums;

namespace Accounting.Models.Entities;

/// <summary>
/// General Ledger / Journal Entry
/// </summary>
public class JournalEntry : TenantEntity
{
    public string EntryNumber { get; set; } = null!;   // running number
    public DateTime EntryDate { get; set; }
    public JournalType JournalType { get; set; } = JournalType.General;  // ประเภทสมุดรายวัน
    public string? Description { get; set; }
    public string? Reference { get; set; }             // เลขอ้างอิง
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;
    public Guid? FiscalPeriodId { get; set; }
    public FiscalPeriod? FiscalPeriod { get; set; }
    public bool IsAutoGenerated { get; set; } = false;  // สร้างอัตโนมัติจากเอกสาร

    /// <summary>
    /// **ใบปิดบัญชี** — ล้างยอดรายได้/ค่าใช้จ่ายเข้ากำไรสะสมตอนปิดรอบ
    /// (<c>YearEndCloseAsync</c>)
    ///
    /// <para>═══ ที่มา (บั๊กจริง · ผลตรวจ C-T02) ═══ ใบปิดบัญชีเป็นรายการ GL ที่
    /// **ถูกต้องและต้องมี** แต่มันคือรายการ *ปิด* งบกำไรขาดทุน ไม่ใช่รายการที่
    /// เกิดจากการดำเนินงาน ⇒ ถ้างบกำไรขาดทุนรวมมันเข้าไปด้วย ยอดของงวดที่ถูกปิด
    /// จะกลายเป็น **ศูนย์** เพราะใบปิดกลับด้านทุกบรรทัดพอดี</para>
    ///
    /// <para>เดิม <c>CloseFiscalPeriodAsync</c> (ปิดงวด<b>รายเดือน</b>) สร้างใบปิด
    /// ทุกเดือน ⇒ ปิดงวด ม.ค. แล้วเปิดงบกำไรขาดทุน ม.ค.–ธ.ค. **รายได้เดือน ม.ค.
    /// เป็น 0** และตัวเลขนี้ไหลต่อไปที่ XBRL ที่ยื่น DBD · ฐาน ภ.ง.ด.51 ·
    /// รายงาน CIT — งบการเงินที่ยื่นออกไปผิดโดยไม่มีอะไรเตือน</para>
    ///
    /// <para>ธงนี้ทำให้ "งบกำไรขาดทุน" คัดใบปิดออกได้ โดย **งบดุล/งบทดลอง/บัญชี
    /// แยกประเภทยังเห็นครบ** (ใบปิดเป็นรายการจริงในสมุดรายวัน ห้ามซ่อน)</para>
    /// </summary>
    public bool IsClosingEntry { get; set; } = false;
    public Guid? SourceDocumentId { get; set; }         // อ้างอิงเอกสารต้นทาง
    public Guid? ReversedByEntryId { get; set; }        // รายการกลับรายการที่สร้างจากรายการนี้
    public Guid? OriginalEntryId { get; set; }          // รายการต้นทางที่ถูกกลับรายการ
    /// <summary>เมื่อ JE นี้เป็น "มัดจำภายนอก" (เช่น JV-INT ที่ integration ลง
    /// Cr 217xx/21913) และถูกนำไปหักบนใบรับเงินสุดท้ายแบบขับ JE
    /// (DepositAppliedDrivesJournal) — FK ไปใบที่หัก. ใช้กัน double-reverse:
    /// drives จะไม่กลับ deferred ของ journal นี้ซ้ำถ้าถูก mark แล้ว.
    /// Null = ยังไม่ถูกนำไปหัก (พฤติกรรมเดิมทุกอย่าง).</summary>
    public Guid? DepositAppliedToDocumentId { get; set; }

    // Project / Branch / Cost Center allocation (header-level default)
    public Guid? ProjectId { get; set; }
    public Project? Project { get; set; }
    public Guid? BranchId { get; set; }
    public Guid? DimensionId { get; set; }              // Cost center / department

    // Free-form metadata
    public string? Note { get; set; }                   // หมายเหตุเพิ่มเติม
    public string? Tags { get; set; }                   // CSV tags e.g. "audit,external,2026Q1"

    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }

    /// <summary>Access-control marker — JEs produced by the payroll run are
    /// stamped Payroll so GL/General Ledger queries can redact them for
    /// users without the matching permission. Default None for the regular
    /// sales / purchase / cash stream.</summary>
    public SensitivityKind Sensitivity { get; set; } = SensitivityKind.None;

    // Navigation
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}

/// <summary>
/// รายการย่อยในใบสำคัญ (Debit/Credit lines)
/// </summary>
public class JournalEntryLine : BaseEntity
{
    public Guid JournalEntryId { get; set; }
    public JournalEntry JournalEntry { get; set; } = null!;
    public Guid AccountId { get; set; }
    public ChartOfAccount Account { get; set; } = null!;

    public decimal DebitAmount { get; set; }
    public decimal CreditAmount { get; set; }
    public string? Description { get; set; }
    public int LineOrder { get; set; }

    // Optional per-line allocation - falls back to header values when null
    public Guid? ProjectId { get; set; }
    public Project? Project { get; set; }
    public Guid? BranchId { get; set; }
    public Guid? DimensionId { get; set; }
    public string? Tags { get; set; }
}

/// <summary>
/// งวดบัญชี (Fiscal Period)
/// </summary>
public class FiscalPeriod : TenantEntity
{
    public string Name { get; set; } = null!;          // e.g. "2567/01"
    public int Year { get; set; }
    public int Month { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public FiscalPeriodStatus Status { get; set; } = FiscalPeriodStatus.Open;

    /// <summary>Soft close — period locked for routine posting but admin
    /// can still adjust. Set by SoftClosePeriodAsync.</summary>
    public DateTime? ClosedAt { get; set; }
    public string? ClosedBy { get; set; }

    /// <summary>Hard close — permanently sealed; only year-end adjustments
    /// allowed. Triggered as part of YearEndCloseAsync.</summary>
    public DateTime? LockedAt { get; set; }
    public string? LockedBy { get; set; }

    /// <summary>The auto-generated JE that closes P&amp;L to Retained Earnings
    /// for this period's year-end. Null for non-terminal months.</summary>
    public Guid? YearEndJournalEntryId { get; set; }

    public ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();
}
