-- รอบ 198 ทีม E — I-1/P-1: นับ JE เก่าที่ลงขาเงินผิดหมวด (อ่านอย่างเดียว · ไม่แก้ข้อมูล · รอเจ้าของตัดสินขอบเขต migration ซ่อม)
-- รอบ 200 ทีม T (คำตัดสินข้อ 20): นักบัญชีเห็นรายการเดียวกันเป็นรายใบที่หน้า "เครื่องมือนักบัญชี → ตรวจโครงสร้างรายการบัญชี" (JournalAnomalyService กฎ JE-LEGACY-* · Helpers/LegacyMoneyLegAudit) — ไฟล์นี้เหลือไว้สำหรับนับยอดรวมทั้งบริษัท
--
-- ที่มา: IntegrationService.CreatePaymentJournalAsync (ก่อนรอบ 198) ลงขาเงินของ banktransfer/promptpay/creditcard
-- ด้วย prefix "112" (= 112xx เงินลงทุนชั่วคราว ในผังมาตรฐาน) · POS ที่ไม่ปักบัญชีบนเครื่องลง QR/โอน/e-Wallet ที่ 112xx
-- และบัตรที่ 113xx ตัวไหนก็ได้ · ทุก query ต้องใส่ :company_id (tenant) — แทนค่าเองก่อนรัน
--
-- 1) JE รับ/จ่ายชำระจาก integration ที่แตะผังหมวด 112 (ตัวเลข = จำนวน JE · ยอด Dr/Cr รวม)
SELECT a."AccountCode", a."AccountName",
       COUNT(DISTINCT je."Id") AS journal_count,
       SUM(l."DebitAmount")    AS total_debit,
       SUM(l."CreditAmount")   AS total_credit,
       MIN(je."EntryDate")     AS first_date,
       MAX(je."EntryDate")     AS last_date
FROM "JournalEntries" je
JOIN "JournalEntryLines" l ON l."JournalEntryId" = je."Id"
JOIN "ChartOfAccounts" a   ON a."Id" = l."AccountId" AND a."CompanyId" = je."CompanyId"
WHERE je."CompanyId" = :company_id
  AND je."IsDeleted" = false
  AND je."IsAutoGenerated" = true
  AND je."JournalType" IN (3, 4)            -- CashReceipts = 3 / CashPayments = 4 (รอบ 200 ทีม T: เดิม (2,3) ผิด — 2 = สมุดซื้อ)
  AND (je."Description" LIKE 'รับชำระ %' OR je."Description" LIKE 'จ่ายชำระ %')
  AND EXISTS (SELECT 1 FROM "Payments" p
              WHERE p."CompanyId" = je."CompanyId" AND p."PaymentNumber" = je."Reference"
                AND p."DocumentId" = je."SourceDocumentId")
  AND a."AccountCode" LIKE '112%'
GROUP BY a."AccountCode", a."AccountName"
ORDER BY a."AccountCode";

-- 2) JE รับชำระจาก integration ที่ลงลูกหนี้ไม่ใช่ 11310 (StartsWith("113") ไม่เรียงเคยได้หัวกลุ่ม/ลูกหนี้อื่น/11340)
SELECT a."AccountCode", a."AccountName", COUNT(DISTINCT je."Id") AS journal_count, SUM(l."CreditAmount") AS total_credit
FROM "JournalEntries" je
JOIN "JournalEntryLines" l ON l."JournalEntryId" = je."Id" AND l."CreditAmount" > 0
JOIN "ChartOfAccounts" a   ON a."Id" = l."AccountId" AND a."CompanyId" = je."CompanyId"
WHERE je."CompanyId" = :company_id
  AND je."IsDeleted" = false
  AND je."Description" LIKE 'รับชำระ %'
  AND a."AccountCode" LIKE '113%' AND a."AccountCode" <> '11310'
GROUP BY a."AccountCode", a."AccountName"
ORDER BY a."AccountCode";

-- 3) JE ขาย POS ที่ขาเงินลงหมวด 112 (QR/โอน/e-Wallet ไม่ได้ปักบัญชีบนเครื่อง) หรือ 113xx ที่ไม่ใช่ 11340 (บัตร)
SELECT a."AccountCode", a."AccountName", COUNT(DISTINCT je."Id") AS journal_count, SUM(l."DebitAmount") AS total_debit
FROM "JournalEntries" je
JOIN "JournalEntryLines" l ON l."JournalEntryId" = je."Id" AND l."DebitAmount" > 0
JOIN "ChartOfAccounts" a   ON a."Id" = l."AccountId" AND a."CompanyId" = je."CompanyId"
WHERE je."CompanyId" = :company_id
  AND je."IsDeleted" = false
  AND l."Description" LIKE 'รับเงิน % POS #%'
  AND (a."AccountCode" LIKE '112%' OR (a."AccountCode" LIKE '113%' AND a."AccountCode" <> '11340'))
GROUP BY a."AccountCode", a."AccountName"
ORDER BY a."AccountCode";
