using Accounting.Helpers;
using Accounting.Models.DTOs;
using Accounting.Models.Entities;
using Accounting.Models.Enums;
using Accounting.Services.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;
using Xunit.Abstractions;

namespace Accounting.Tests.Db;

/// <summary>
/// รอบ 203 ทีม F3 — <b>golden ของวงจร ภ.พ.36 ทั้งเส้นบน PostgreSQL จริง</b> (PP36_REVIEW E-2/E-3/E-4/E-5/E-6 · คำตัดสินข้อ 129, 133, 134, 136)
///
/// <para>เคสผู้ใช้ PV-20260901-0001 (Booking.com B.V. ค่าคอมมิชชั่น 5,908 · VAT ประเมินเอง 413.56): จ่ายเดือน "ก.ย." → นำส่ง ภ.พ.36 → ยอดค้าง 0 →
/// ได้ใบเสร็จกรมสรรพากรเดือน "ต.ค." → รับรู้ (Dr 11610/Cr 11640 ลงวันใบเสร็จ) → ภ.พ.30 ต.ค. เคลม 413.56 ครั้งเดียว (ก.ย. ไม่เคลม) →
/// ยอดคงเหลือ 21912 และ 11640 = 0</para>
/// <para>ทิศตรงข้าม: ใบอนุมัติแล้วไม่มี JE ไม่ถูกนับ/นำส่ง/รับรู้ (ขึ้นเป็นรายการต้องซ่อม) · ใบอนุมัติหลังนำส่ง ⇒ นำส่งเพิ่มเติมงวดเดิมได้ และไม่ถูกรับรู้ก่อนนำส่ง ·
/// ยกเลิก/ปลดธงหลังนำส่งถูกบล็อก (ด่าน <c>Pp36Ledger.ChangeBlocksAsync</c> ตัวเดียวที่ VoidDocumentAsync/Reclassify/รอบโอนเรียก) · ใบ USD นำส่งเป็นบาท</para>
/// <para>วันที่อิงเดือนปัจจุบัน (ไม่ฝังปี) — "ก.ย." = 3 เดือนก่อน · "ต.ค." = 2 เดือนก่อน · JE ห้ามลงวันอนาคต</para>
/// </summary>
[Trait("Category", "Db")]
public class Pp36LifecycleGoldenDbTests
{
    private readonly ITestOutputHelper _out;
    public Pp36LifecycleGoldenDbTests(ITestOutputHelper output) => _out = output;

    private static readonly DateTime Sep = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1).AddMonths(-3);
    private static readonly DateTime Oct = Sep.AddMonths(1);

    private sealed record Seed(Guid CompanyId, Guid ContactId, Dictionary<string, Guid> Acc);

    private static async Task<Seed> SeedAsync(Accounting.Data.AccountingDbContext db, bool vatRegistered = true)
    {
        var company = new Company { Name = "บริษัททดสอบ ภ.พ.36", TaxId = "0105556000001", IsVatRegistered = vatRegistered };
        db.Companies.Add(company);
        await db.SaveChangesAsync();
        var acc = new Dictionary<string, Guid>();
        foreach (var (code, name, type) in new[]
        {
            ("11120", "เงินฝากธนาคาร", AccountType.Asset),
            ("11610", "ภาษีซื้อ", AccountType.Asset),
            ("11640", "ภาษีซื้อยังไม่ถึงกำหนด", AccountType.Asset),
            ("21912", "ภาษีมูลค่าเพิ่มค้างนำส่ง ภ.พ.36", AccountType.Liability),
            ("52150", "ค่าคอมมิชชั่น", AccountType.Expense),
            ("54820", "ค่าปรับ/เบี้ยปรับ", AccountType.Expense),
        })
        {
            var a = new ChartOfAccount { CompanyId = company.Id, AccountCode = code, AccountName = name, AccountType = type, Level = 4, IsActive = true };
            db.ChartOfAccounts.Add(a);
            acc[code] = a.Id;
        }
        var contact = new Contact { CompanyId = company.Id, Name = "Booking.com B.V.", IsSupplier = true, CountryCode = "NL" };
        db.Contacts.Add(contact);
        await db.SaveChangesAsync();
        return new Seed(company.Id, contact.Id, acc);
    }

    /// <summary>ใบสำคัญจ่ายบริการต่างประเทศที่อนุมัติแล้ว (+ JE §83/6 ถ้า <paramref name="withJournal"/>) — JE seed ตรงผ่าน DbContext
    /// ทรงเดียวกับ AutoPost: Dr ค่าใช้จ่าย ฐาน · Dr 11640 VAT / Cr 21912 VAT · Cr ธนาคาร ฐาน (บาท)</summary>
    private static async Task<Document> SeedPvAsync(Accounting.Data.AccountingDbContext db, Seed s, string number, DateTime paidOn,
        decimal baseAmt, decimal vat, bool withJournal, decimal fx = 1m, string currency = "THB",
        DocumentType type = DocumentType.PaymentVoucher, bool paid = true)
    {
        var doc = new Document
        {
            CompanyId = s.CompanyId, ContactId = s.ContactId, DocumentNumber = number, DocumentType = type,
            Status = paid ? DocumentStatus.Paid : DocumentStatus.Approved, DocumentDate = paidOn,
            PaymentDate = paid ? paidOn : null, TaxPointDate = paidOn,
            IsForeignService = true, SubTotal = baseAmt, VatAmount = vat, TotalAmount = baseAmt + vat,
            Currency = currency, ExchangeRate = fx, InputVatPostedAsUndue = true,
        };
        doc.Lines.Add(new DocumentLine
        {
            LineOrder = 1, Description = "Commission", Quantity = 1, UnitPrice = baseAmt, Amount = baseAmt, VatRate = 7, VatAmount = vat,
            AccountId = s.Acc["52150"], IsVatClaimable = true,
        });
        db.Documents.Add(doc);
        await db.SaveChangesAsync();
        if (withJournal)
        {
            decimal B(decimal x) => DocumentFx.ToBaht(x, fx);
            var je = new JournalEntry
            {
                CompanyId = s.CompanyId, EntryNumber = "JV-" + number, EntryDate = paidOn, Status = JournalEntryStatus.Posted,
                JournalType = JournalType.CashPayments, SourceDocumentId = doc.Id, IsAutoGenerated = true,
                TotalDebit = B(baseAmt) + B(vat), TotalCredit = B(baseAmt) + B(vat),
            };
            je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["52150"], DebitAmount = B(baseAmt), LineOrder = 1 });
            je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["11640"], DebitAmount = B(vat), LineOrder = 2 });
            je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["21912"], CreditAmount = B(vat), LineOrder = 3 });
            je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["11120"], CreditAmount = B(baseAmt), LineOrder = 4 });
            db.JournalEntries.Add(je);
            await db.SaveChangesAsync();
        }
        return doc;
    }

    private static StatutoryRemittanceService Svc(Accounting.Data.AccountingDbContext db)
        => new(db, new AccountingService(db), NullLogger<StatutoryRemittanceService>.Instance, new TaxService(db));

    private static async Task<decimal> BalanceAsync(Accounting.Data.AccountingDbContext db, Guid companyId, string code)
        => await (from l in db.JournalEntryLines.AsNoTracking()
                  join j in db.JournalEntries.AsNoTracking() on l.JournalEntryId equals j.Id
                  join a in db.ChartOfAccounts.AsNoTracking() on l.AccountId equals a.Id
                  where j.CompanyId == companyId && j.Status == JournalEntryStatus.Posted && a.AccountCode == code
                  select l.DebitAmount - l.CreditAmount).SumAsync();

    private static RemitRequest Remit(Seed s, DateTime period, DateTime payDate, string? filing = null) => new(
        "VatPp36", period.Year, period.Month, payDate, BankGlAccountId: s.Acc["11120"], FilingNumber: filing);

    [Fact]
    public async Task ก_นำส่งกันยา_รับรู้ลงวันใบเสร็จตุลา_ภพ30ตุลาเคลมครั้งเดียว_21912และ11640เหลือศูนย์()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL (ACCOUNTING_TEST_PG) — ข้าม · หลักฐานอยู่ที่ job db-test"); return; }
        var s = await SeedAsync(db);
        var pv = await SeedPvAsync(db, s, "PV-G-0001", Sep.AddDays(14), 5908m, 413.56m, withJournal: true);
        var svc = Svc(db);

        var dash = await svc.GetDashboardAsync(s.CompanyId, 24);
        var item = Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36"));
        Assert.Equal(413.56m, item.Amount);
        Assert.Equal((Sep.Year, Sep.Month), (item.PeriodYear, item.PeriodMonth));

        // ภ.พ.36 ก.ย. (ตัวสร้างรายงานใช้ตัวโหลดเดียวกัน) = 413.56
        var pp36Report = await new TaxService(db).ComputePp36ReportAsync(s.CompanyId, Sep.Year, Sep.Month);
        Assert.Equal(413.56m, pp36Report.OutputVat);

        // นำส่งภายในเดือน ก.ย. (ก่อนกำหนด ⇒ ไม่มีเงินเพิ่ม)
        var remit = await svc.RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20)), "tester");
        Assert.Equal(413.56m, remit.Amount);
        Assert.Equal(0m, remit.LateFee);

        using (var check = DbTestDatabase.TryCreateContext()!)
        {
            var link = Assert.Single(await check.Pp36RemittanceDocuments.AsNoTracking()
                .Where(x => x.CompanyId == s.CompanyId).ToListAsync());
            Assert.Equal(pv.Id, link.DocumentId);
            Assert.Equal(413.56m, link.VatAmount);
            Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "21912"));          // นำส่งล้าง 21912 พอดี
        }

        var after = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.DoesNotContain(after.Pending, p => p.RemittanceType == "VatPp36");     // ยอดค้าง 0
        var awaiting = Assert.Single(after.Pp36AwaitingRecognition);
        Assert.Equal(413.56m, awaiting.VatAmount);
        Assert.Equal(remit.Id, awaiting.RemittanceId);

        // ไม่มีเลขใบเสร็จ ⇒ รับรู้ไม่ได้ (คำตัดสินข้อ 136)
        var noReceipt = await Assert.ThrowsAsync<BusinessRuleException>(() => Svc(db).RecognizePp36InputVatAsync(
            s.CompanyId, Sep.Year, Sep.Month, null, "tester"));
        Assert.Equal(Pp36Lifecycle.RuleNoReceipt, noReceipt.RuleCode);
        db.ChangeTracker.Clear();

        // วันเคลมก่อนวันใบเสร็จ ⇒ ปฏิเสธ (คำตัดสินข้อ 129)
        var receiptDate = Oct.AddDays(4);
        var early = await Assert.ThrowsAsync<BusinessRuleException>(() => Svc(db).RecognizePp36InputVatAsync(
            s.CompanyId, Sep.Year, Sep.Month, Sep.AddDays(25), "tester", "RD-0001", receiptDate));
        Assert.Equal(Pp36Lifecycle.RuleClaimBeforeReceipt, early.RuleCode);
        db.ChangeTracker.Clear();

        // รับรู้ — วันเคลมค่าเริ่มต้น = วันที่ใบเสร็จ ต.ค. · JE ลงวันเดียวกัน
        var rec = await Svc(db).RecognizePp36InputVatAsync(s.CompanyId, Sep.Year, Sep.Month, null, "tester", "RD-0001", receiptDate);
        Assert.Equal(413.56m, rec.Amount);
        using (var check = DbTestDatabase.TryCreateContext()!)
        {
            var je = await check.JournalEntries.AsNoTracking().SingleAsync(j => j.Id == rec.JournalEntryId && j.CompanyId == s.CompanyId);
            Assert.Equal(receiptDate.Date, je.EntryDate.Date);
            var d = await check.Documents.AsNoTracking().SingleAsync(x => x.Id == pv.Id && x.CompanyId == s.CompanyId);
            Assert.Equal(receiptDate.Date, d.InputVatBecameClaimableAt!.Value.Date);
            Assert.Equal(receiptDate.Date, d.Pp36RdReceiptDate!.Value.Date);
            Assert.Equal("RD-0001", d.Pp36RdReceiptNumber);
            Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "21912"));
            Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "11640"));
            Assert.Equal(413.56m, await BalanceAsync(check, s.CompanyId, "11610"));

            // ภ.พ.30 ต.ค. เคลม 413.56 · ก.ย. ไม่เคลม (ครั้งเดียว)
            var taxCheck = new TaxService(check);
            var octPp30 = await taxCheck.ComputeVatReportAsync(s.CompanyId, Oct.Year, Oct.Month);
            Assert.Equal(413.56m, octPp30.Lines.Where(l => l.DocumentId == pv.Id && l.IncomeTypeCode == "INPUT" && !l.IsExcluded).Sum(l => l.TaxAmount));
            var sepPp30 = await taxCheck.ComputeVatReportAsync(s.CompanyId, Sep.Year, Sep.Month);
            Assert.DoesNotContain(sepPp30.Lines, l => l.DocumentId == pv.Id && l.IncomeTypeCode == "INPUT" && !l.IsExcluded);

            // ยกเลิก/ปลดธง/ปรับยอดหลังนำส่ง+รับรู้ ⇒ บล็อก (คำตัดสินข้อ 134)
            var blocks = await Pp36Ledger.ChangeBlocksAsync(check, s.CompanyId, new[] { pv.Id }, "ยกเลิก");
            Assert.Contains("ยกเลิกใบ PV-G-0001 ไม่ได้", blocks[pv.Id]);
        }

        // รับรู้ซ้ำ ⇒ ไม่มีอะไรค้าง (ไม่ลง JE ซ้ำ)
        await Assert.ThrowsAsync<InvalidOperationException>(() => Svc(db).RecognizePp36InputVatAsync(
            s.CompanyId, Sep.Year, Sep.Month, null, "tester", "RD-0001", receiptDate));
    }

    [Fact]
    public async Task ข_ใบอนุมัติแล้วไม่มีJE_ไม่ถูกนับไม่ถูกนำส่ง_ขึ้นเป็นรายการต้องซ่อม()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var pv = await SeedPvAsync(db, s, "PV-G-NOJE", Sep.AddDays(1), 5908m, 413.56m, withJournal: false);
        var svc = Svc(db);

        var dash = await svc.GetDashboardAsync(s.CompanyId, 24);
        Assert.DoesNotContain(dash.Pending, p => p.RemittanceType == "VatPp36");
        var issue = Assert.Single(dash.Pp36Issues!);
        Assert.Equal("NoJournal", issue.Kind);
        Assert.Equal(pv.Id, issue.DocumentId);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => svc.RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20)), "tester"));
        Assert.Contains("PV-G-NOJE", ex.Message);
        Assert.Equal(0m, (await new TaxService(db).ComputePp36ReportAsync(s.CompanyId, Sep.Year, Sep.Month)).OutputVat);
        Assert.False(await db.Pp36RemittanceDocuments.AnyAsync(x => x.CompanyId == s.CompanyId));
        var states = await Pp36Ledger.StatesAsync(db, s.CompanyId, new[] { pv.Id });
        Assert.Equal(Pp36DocState.NoJournal, states[pv.Id].State);
        // ยังไม่นำส่ง ⇒ ยกเลิกได้ตามเดิม (ด่านไม่ฟ้อง)
        Assert.Empty(await Pp36Ledger.ChangeBlocksAsync(db, s.CompanyId, new[] { pv.Id }, "ยกเลิก"));
    }

    [Fact]
    public async Task ค_ใบอนุมัติหลังนำส่ง_ไม่ถูกรับรู้ก่อนนำส่ง_นำส่งเพิ่มเติมงวดเดิมได้()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var first = await SeedPvAsync(db, s, "PV-G-A", Sep.AddDays(3), 1000m, 70m, withJournal: true);
        var r1 = await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20), "RD-A"), "tester");
        Assert.Equal(70m, r1.Amount);

        // ใบที่สองของงวดเดียวกัน อนุมัติหลังนำส่ง
        var second = await SeedPvAsync(db, s, "PV-G-B", Sep.AddDays(10), 2000m, 140m, withJournal: true);
        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.Equal(140m, Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36")).Amount);

        // รับรู้ก่อนนำส่งใบที่สอง ⇒ รับรู้เฉพาะใบแรก (ใบที่สองยังไม่ได้นำส่ง = ห้ามเคลม)
        var rec = await Svc(db).RecognizePp36InputVatAsync(s.CompanyId, Sep.Year, Sep.Month, null, "tester", null, Oct.AddDays(1));
        Assert.Equal(70m, rec.Amount);
        using (var check = DbTestDatabase.TryCreateContext()!)
        {
            Assert.Null((await check.Documents.AsNoTracking().SingleAsync(d => d.Id == second.Id && d.CompanyId == s.CompanyId)).InputVatBecameClaimableAt);
            Assert.NotNull((await check.Documents.AsNoTracking().SingleAsync(d => d.Id == first.Id && d.CompanyId == s.CompanyId)).InputVatBecameClaimableAt);
        }

        // นำส่งเพิ่มเติมงวดเดิม (คำตัดสินข้อ 133) — นับเฉพาะใบที่สอง
        var r2 = await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(25), "RD-B"), "tester");
        Assert.Equal(140m, r2.Amount);
        using (var check = DbTestDatabase.TryCreateContext()!)
        {
            var links = await check.Pp36RemittanceDocuments.AsNoTracking().Where(x => x.CompanyId == s.CompanyId).ToListAsync();
            Assert.Equal(2, links.Count);
            Assert.Equal(second.Id, links.Single(l => l.StatutoryRemittanceId == r2.Id).DocumentId);
            Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "21912"));
        }
        var dash2 = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.DoesNotContain(dash2.Pending, p => p.RemittanceType == "VatPp36");
        // ไม่มีอะไรค้างแล้ว ⇒ นำส่งอีกรอบถูกปฏิเสธ (ห้ามนับใบเดิมซ้ำ)
        await Assert.ThrowsAsync<InvalidOperationException>(() => Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(26)), "tester"));
    }

    [Fact]
    public async Task ง_ใบUSD_ยอดค้างและนำส่งเป็นบาทตามJE()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        await SeedPvAsync(db, s, "PV-G-USD", Sep.AddDays(5), 1000m, 70m, withJournal: true, fx: 36m, currency: "USD");
        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.Equal(2520m, Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36")).Amount);
        var report = await new TaxService(db).ComputePp36ReportAsync(s.CompanyId, Sep.Year, Sep.Month);
        var line = Assert.Single(report.Lines);
        Assert.Equal(2520m, line.TaxAmount);
        Assert.Equal(36000m, line.IncomeAmount);
        var r = await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20)), "tester");
        Assert.Equal(2520m, r.Amount);
    }

    [Fact]
    public async Task จ_บริษัทไม่จดVAT_นำส่งได้_ไม่มีภาษีซื้อให้รับรู้()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db, vatRegistered: false);
        // JE ทรงบริษัทไม่จด VAT: VAT ประเมินเองเป็นค่าใช้จ่าย (ไม่พัก 11640)
        var doc = new Document
        {
            CompanyId = s.CompanyId, ContactId = s.ContactId, DocumentNumber = "PV-G-NOVAT", DocumentType = DocumentType.PaymentVoucher,
            Status = DocumentStatus.Paid, DocumentDate = Sep.AddDays(2), PaymentDate = Sep.AddDays(2), IsForeignService = true,
            SubTotal = 1000m, VatAmount = 70m, TotalAmount = 1070m,
        };
        db.Documents.Add(doc);
        await db.SaveChangesAsync();
        var je = new JournalEntry
        {
            CompanyId = s.CompanyId, EntryNumber = "JV-NOVAT", EntryDate = doc.DocumentDate, Status = JournalEntryStatus.Posted,
            SourceDocumentId = doc.Id, TotalDebit = 1070m, TotalCredit = 1070m,
        };
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["52150"], DebitAmount = 1070m, LineOrder = 1 });
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["21912"], CreditAmount = 70m, LineOrder = 2 });
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["11120"], CreditAmount = 1000m, LineOrder = 3 });
        db.JournalEntries.Add(je);
        await db.SaveChangesAsync();

        var r = await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20), "RD-X"), "tester");
        Assert.Equal(70m, r.Amount);
        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.Empty(dash.Pp36AwaitingRecognition);          // ไม่มีอะไรให้รับรู้ (เดิมรับรู้ VatAmount ทั้งก้อน ⇒ 11640 ติดลบ)
        await Assert.ThrowsAsync<InvalidOperationException>(() => Svc(db).RecognizePp36InputVatAsync(
            s.CompanyId, Sep.Year, Sep.Month, null, "tester", null, Oct.AddDays(1)));
    }

    /// <summary>ใบลด/เพิ่มหนี้ของใบเจ้าของ ภ.พ.36 — JE ผูกเลขของใบลด/เพิ่มหนี้เอง (ทีม F2 E-7) ทรงเดียวกับ AutoPost</summary>
    private static async Task SeedNoteAsync(Accounting.Data.AccountingDbContext db, Seed s, Document owner, string number, bool credit,
        decimal baseAmt, decimal vat)
    {
        var note = new Document
        {
            CompanyId = s.CompanyId, ContactId = s.ContactId, DocumentNumber = number,
            DocumentType = credit ? DocumentType.CreditNote : DocumentType.DebitNote, Status = DocumentStatus.Approved,
            DocumentDate = owner.DocumentDate.AddDays(2), RelatedDocumentId = owner.Id, IsForeignService = true,
            SubTotal = baseAmt, VatAmount = vat, TotalAmount = baseAmt + vat,
        };
        db.Documents.Add(note);
        await db.SaveChangesAsync();
        var je = new JournalEntry
        {
            CompanyId = s.CompanyId, EntryNumber = "JV-" + number, EntryDate = note.DocumentDate, Status = JournalEntryStatus.Posted,
            JournalType = JournalType.Purchase, SourceDocumentId = note.Id, TotalDebit = baseAmt + vat, TotalCredit = baseAmt + vat,
        };
        // ใบลดหนี้ซื้อ: Dr ผู้รับเงิน ฐาน · Dr 21912 VAT / Cr ค่าใช้จ่าย ฐาน · Cr 11640 VAT — ใบเพิ่มหนี้กลับทิศ
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["11120"], DebitAmount = credit ? baseAmt : 0, CreditAmount = credit ? 0 : baseAmt, LineOrder = 1 });
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["21912"], DebitAmount = credit ? vat : 0, CreditAmount = credit ? 0 : vat, LineOrder = 2 });
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["52150"], DebitAmount = credit ? 0 : baseAmt, CreditAmount = credit ? baseAmt : 0, LineOrder = 3 });
        je.Lines.Add(new JournalEntryLine { AccountId = s.Acc["11640"], DebitAmount = credit ? 0 : vat, CreditAmount = credit ? vat : 0, LineOrder = 4 });
        db.JournalEntries.Add(je);
        await db.SaveChangesAsync();
    }

    [Theory]
    [InlineData(true, 343.56)]    // ใบลดหนี้ VAT 70 ก่อนนำส่ง ⇒ 413.56 − 70
    [InlineData(false, 483.56)]   // ใบเพิ่มหนี้ VAT 70 ก่อนนำส่ง ⇒ 413.56 + 70
    public async Task ฉ_ใบลดหรือเพิ่มหนี้ก่อนนำส่ง_ยอดนำส่งและรับรู้ตามGLสุทธิ_คงเหลือศูนย์(bool credit, double expected)
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var pi = await SeedPvAsync(db, s, "PI-G-CN", Sep.AddDays(3), 5908m, 413.56m, withJournal: true, type: DocumentType.PurchaseInvoice);
        await SeedNoteAsync(db, s, pi, credit ? "CN-G-1" : "DN-G-1", credit, 1000m, 70m);
        var want = (decimal)expected;

        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.Equal(want, Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36")).Amount);
        Assert.Equal(want, (await new TaxService(db).ComputePp36ReportAsync(s.CompanyId, Sep.Year, Sep.Month)).OutputVat);
        var r = await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20), "RD-N"), "tester");
        Assert.Equal(want, r.Amount);
        var rec = await Svc(db).RecognizePp36InputVatAsync(s.CompanyId, Sep.Year, Sep.Month, null, "tester", null, Oct.AddDays(2));
        Assert.Equal(want, rec.Amount);
        using var check = DbTestDatabase.TryCreateContext()!;
        Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "21912"));
        Assert.Equal(0m, await BalanceAsync(check, s.CompanyId, "11640"));
        Assert.Equal(want, await BalanceAsync(check, s.CompanyId, "11610"));
    }

    [Fact]
    public async Task ช_ใบAนำส่งแล้ว_ใบBไม่มีJEงวดเดียวกัน_ซ่อมได้_แล้วขึ้นยอดค้างนำส่งเพิ่มเติม()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var a = await SeedPvAsync(db, s, "PV-G-RA", Sep.AddDays(2), 1000m, 70m, withJournal: true);
        await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20), "RD-RA"), "tester");
        var b = await SeedPvAsync(db, s, "PV-G-RB", Sep.AddDays(4), 2000m, 140m, withJournal: false);

        // ด่านเครื่องมือซ่อมตัดสินต่อใบ (เดิมระดับงวด ⇒ ใบ B ถูกปฏิเสธว่า "งวดนำส่งแล้ว" ตลอดไป)
        var docs = new DocumentService(db, new AccountingService(db), null!, null!, null!,
            NullLogger<DocumentService>.Instance, null!, null!, null!);
        var decision = await docs.GetMissingJournalStatusAsync(s.CompanyId, b.Id);
        Assert.True(decision.Missing);
        Assert.True(decision.CanRepair, decision.Message);
        // ทิศตรงข้าม: ใบ A อยู่ในรายการนำส่งแล้ว (ตัวตรวจเดียวกับด่านยกเลิก/เครื่องมือซ่อม)
        Assert.True((await Pp36Ledger.RemittedStatusAsync(db, s.CompanyId, new[] { a.Id })).ContainsKey(a.Id));
        Assert.False((await Pp36Ledger.RemittedStatusAsync(db, s.CompanyId, new[] { b.Id })).ContainsKey(b.Id));

        // ซ่อมแล้ว (JE ทรงเดียวกับ AutoPost) ⇒ ใบ B ขึ้นเป็นยอดค้างนำส่งเพิ่มเติมงวดเดิม
        db.JournalEntries.Add(new JournalEntry
        {
            CompanyId = s.CompanyId, EntryNumber = "JV-RB", EntryDate = b.DocumentDate, Status = JournalEntryStatus.Posted,
            SourceDocumentId = b.Id, TotalDebit = 2140m, TotalCredit = 2140m,
            Lines = new List<JournalEntryLine>
            {
                new() { AccountId = s.Acc["52150"], DebitAmount = 2000m, LineOrder = 1 },
                new() { AccountId = s.Acc["11640"], DebitAmount = 140m, LineOrder = 2 },
                new() { AccountId = s.Acc["21912"], CreditAmount = 140m, LineOrder = 3 },
                new() { AccountId = s.Acc["11120"], CreditAmount = 2000m, LineOrder = 4 },
            },
        });
        await db.SaveChangesAsync();
        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        Assert.Equal(140m, Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36")).Amount);
    }

    [Fact]
    public async Task ซ_ใบซื้อเครดิตลงปลายเดือน_จ่ายเดือนถัดไป_งวดภพ36คือเดือนที่จ่าย_ใบที่นำส่งแล้วไม่ย้าย()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var aug25 = Sep.AddDays(-7);
        var pi = await SeedPvAsync(db, s, "PI-G-CR", aug25, 5908m, 413.56m, withJournal: true, type: DocumentType.PurchaseInvoice, paid: false);
        Assert.Null(pi.PaymentDate);

        var tracked = await db.Documents.SingleAsync(d => d.Id == pi.Id && d.CompanyId == s.CompanyId);
        Assert.True(await Pp36Ledger.StampFirstPaymentAsync(db, s.CompanyId, tracked, Sep.AddDays(9)));
        await db.SaveChangesAsync();
        Assert.False(await Pp36Ledger.StampFirstPaymentAsync(db, s.CompanyId, tracked, Sep.AddDays(20)));   // จ่ายครั้งที่สองไม่ย้ายงวด

        var dash = await Svc(db).GetDashboardAsync(s.CompanyId, 24);
        var item = Assert.Single(dash.Pending.Where(p => p.RemittanceType == "VatPp36"));
        Assert.Equal((Sep.Year, Sep.Month), (item.PeriodYear, item.PeriodMonth));   // งวดที่จ่าย ไม่ใช่งวดวันที่ใบ

        // ทิศตรงข้าม: ใบที่อยู่ในรายการนำส่งแล้วแต่ยังไม่มีวันจ่าย (ข้อมูลเดิม) ⇒ ไม่ย้ายงวด
        var pi2 = await SeedPvAsync(db, s, "PI-G-CR2", Oct.AddDays(1), 1000m, 70m, withJournal: true, type: DocumentType.PurchaseInvoice, paid: false);
        await Svc(db).RemitAsync(s.CompanyId, Remit(s, Oct, Oct.AddDays(5), "RD-CR2"), "tester");
        var tracked2 = await db.Documents.SingleAsync(d => d.Id == pi2.Id && d.CompanyId == s.CompanyId);
        Assert.False(await Pp36Ledger.StampFirstPaymentAsync(db, s.CompanyId, tracked2, Oct.AddMonths(1)));
        Assert.Null(tracked2.PaymentDate);
    }

    [Fact]
    public async Task ฌ_ภพ30_ใบUSDเคลมเป็นบาทเท่ากับGL_ใบบาทไม่เปลี่ยน()
    {
        using var db = DbTestDatabase.TryCreateContext();
        if (db == null) { _out.WriteLine("ไม่มีฐาน PostgreSQL — ข้าม"); return; }
        var s = await SeedAsync(db);
        var usd = await SeedPvAsync(db, s, "PV-G-USD30", Sep.AddDays(5), 1000m, 70m, withJournal: true, fx: 36m, currency: "USD");
        var thb = await SeedPvAsync(db, s, "PV-G-THB30", Sep.AddDays(6), 5908m, 413.56m, withJournal: true);
        await Svc(db).RemitAsync(s.CompanyId, Remit(s, Sep, Sep.AddDays(20), "RD-FX"), "tester");
        await Svc(db).RecognizePp36InputVatAsync(s.CompanyId, Sep.Year, Sep.Month, null, "tester", null, Oct.AddDays(1));
        var pp30 = await new TaxService(db).ComputeVatReportAsync(s.CompanyId, Oct.Year, Oct.Month);
        decimal Claimed(Guid id) => pp30.Lines.Where(l => l.DocumentId == id && l.IncomeTypeCode == "INPUT" && !l.IsExcluded).Sum(l => l.TaxAmount);
        Assert.Equal(2520m, Claimed(usd.Id));      // = Dr 11610 ใน GL (เดิม 70)
        Assert.Equal(413.56m, Claimed(thb.Id));    // ใบบาทไม่เปลี่ยนแม้แต่สตางค์
    }
}
