using Xunit;

namespace Accounting.Tests;

/// <summary>
/// "ปุ่มที่โชว์ = สิ่งที่ทำได้จริง" — ตารางความจริงของ guard ฝั่ง server
/// (AccountingService) ที่หน้าสมุดรายวันต้องสะท้อนให้ตรง
///
/// ที่มา: ใบสำคัญที่ระบบลงให้จากเอกสาร (PV/INV auto-post) โชว์ปุ่มครบทั้ง 5 ตัว
/// แต่ server บล็อก 4 ตัว ⇒ นักบัญชีกดแล้วเจอ error ทีละปุ่มโดยไม่รู้ว่าจริง ๆ
/// ต้องไปแก้ที่ไหน (คำถามผู้ใช้: "จะแก้ผังบัญชีที่ลง JE ไปแล้ว แก้ตรงไหน")
///
/// guard จริงที่ mirror ไว้:
///   UpdateJournalEntryAsync  — บล็อกเมื่อ IsAutoGenerated หรือ SourceDocumentId != null
///   ReverseJournalEntryAsync — ต้อง Posted · ไม่เคยถูกกลับ · ไม่ใช่ตัวกลับ (OriginalEntryId)
///                              · ไม่ผูกเอกสาร (SourceDocumentId) เมื่อ !systemTriggered
///   CorrectJournalEntryAsync — ต้อง Posted · ไม่เคยถูกกลับ · ไม่ผูกเอกสาร
///   VoidJournalEntryAsync    — ไม่ใช่ตัวกลับ · ไม่ผูกเอกสาร
///   DeleteJournalEntryAsync  — ไม่ผูกเอกสาร
/// </summary>
public class JournalEntryActionGuardTests
{
    private sealed record Je(
        string Status,
        bool FromDocument = false,
        bool IsReversalEntry = false,
        bool AlreadyReversed = false);

    private static bool CanEdit(Je j) => !j.FromDocument;
    private static bool CanPost(Je j) => !j.FromDocument && j.Status == "Draft";
    private static bool CanReverse(Je j) =>
        !j.FromDocument && j.Status == "Posted" && !j.IsReversalEntry && !j.AlreadyReversed;
    private static bool CanCorrect(Je j) => CanReverse(j);   // Correct = Reverse + clone
    private static bool CanDelete(Je j) => !j.FromDocument;

    /// <summary>ชุดปุ่มที่ UI ต้องแสดง (เรียงตามลำดับบนแถว)</summary>
    private static string[] Buttons(Je j)
    {
        var b = new List<string> { "ดู" };
        if (j.FromDocument) { b.Add("เปิดเอกสารต้นทาง"); return b.ToArray(); }
        if (CanPost(j)) b.Add("ผ่านรายการ");
        if (CanEdit(j)) b.Add("แก้ไข");
        if (CanCorrect(j)) b.Add("กลับ-แก้");
        if (CanReverse(j)) b.Add("กลับรายการ");
        if (CanDelete(j)) b.Add("ลบ");
        return b.ToArray();
    }

    [Fact]
    public void Document_sourced_entry_offers_only_view_and_open_document()
    {
        // ใบที่ระบบลงจากเอกสาร — ทุกคำสั่งแก้ไขถูกบล็อกฝั่ง server ⇒ ห้ามโชว์ปุ่ม
        var je = new Je("Posted", FromDocument: true);
        Assert.Equal(new[] { "ดู", "เปิดเอกสารต้นทาง" }, Buttons(je));
        Assert.False(CanEdit(je));
        Assert.False(CanReverse(je));
        Assert.False(CanCorrect(je));
        Assert.False(CanDelete(je));
    }

    [Fact]
    public void Manual_posted_entry_offers_the_full_correction_toolkit()
    {
        var je = new Je("Posted");
        Assert.Equal(new[] { "ดู", "แก้ไข", "กลับ-แก้", "กลับรายการ", "ลบ" }, Buttons(je));
    }

    [Fact]
    public void Manual_draft_gets_post_but_not_reverse()
    {
        // ยังไม่ผ่านรายการ = ยังไม่มีผลต่องบ ⇒ ไม่มีอะไรให้กลับ
        var je = new Je("Draft");
        Assert.Equal(new[] { "ดู", "ผ่านรายการ", "แก้ไข", "ลบ" }, Buttons(je));
        Assert.False(CanReverse(je));
    }

    [Fact]
    public void Reversal_entry_cannot_be_reversed_again()
    {
        // กลับ "ตัวกลับ" = ใส่ยอดเดิมกลับเข้าไป ทำ audit trail สับสน
        var je = new Je("Posted", IsReversalEntry: true);
        Assert.False(CanReverse(je));
        Assert.False(CanCorrect(je));
        Assert.Equal(new[] { "ดู", "แก้ไข", "ลบ" }, Buttons(je));
    }

    [Fact]
    public void Already_reversed_entry_cannot_be_reversed_twice()
    {
        var je = new Je("Posted", AlreadyReversed: true);
        Assert.False(CanReverse(je));
        Assert.False(CanCorrect(je));
    }

    [Theory]
    [InlineData("Posted")]
    [InlineData("Draft")]
    [InlineData("Reversed")]
    [InlineData("Voided")]
    public void Document_link_is_the_only_action_regardless_of_status(string status)
    {
        // ไม่ว่าเอกสารจะอยู่สถานะไหน ทางแก้ก็อยู่ที่เอกสารเสมอ — ไม่มีสถานะไหน
        // ที่ปลดล็อกให้แก้ JE ตรง ๆ ได้
        var je = new Je(status, FromDocument: true);
        Assert.Equal(new[] { "ดู", "เปิดเอกสารต้นทาง" }, Buttons(je));
    }

    [Fact]
    public void Batch_selection_excludes_document_sourced_rows()
    {
        // BatchVoid/BatchDelete ฝั่ง server "ปฏิเสธทั้งชุด" ถ้ามีใบต้องห้ามปนมา
        // ⇒ ติ๊กไม่ได้ตั้งแต่แรก ไม่ใช่ให้ติ๊กแล้วค่อยแจ้ง error ตอนกดลบ
        static bool CanSelect(Je j) => j.Status != "Reversed" && !j.FromDocument;
        Assert.True(CanSelect(new Je("Posted")));
        Assert.False(CanSelect(new Je("Posted", FromDocument: true)));
        Assert.False(CanSelect(new Je("Reversed")));
    }

    /// <summary>ทางแก้ผังบัญชีของใบที่ผูกเอกสาร — ต้องมีทางที่ใช้ได้จริงเสมอ
    /// (ไม่งั้น "แก้ไม่ได้เลย" ซึ่งเป็นสิ่งที่ผู้ใช้เจอ)</summary>
    [Theory]
    [InlineData("Expense", true)]
    [InlineData("PurchaseInvoice", true)]
    [InlineData("PaymentVoucher", true)]
    [InlineData("Invoice", false)]          // ฝั่งขาย — ต้องยกเลิกแล้วออกใหม่
    [InlineData("TaxInvoice", false)]
    public void Reclassify_line_availability_matches_document_type(string docType, bool expected)
    {
        // mirror ของ documents.html canReclassify + DocumentService.ReclassifyLineAccountAsync
        var allowed = new[] { "Expense", "PurchaseInvoice", "PaymentVoucher" };
        Assert.Equal(expected, allowed.Contains(docType));
    }

    [Theory]
    [InlineData("Approved", true)]
    [InlineData("Sent", true)]
    [InlineData("PartiallyPaid", true)]
    [InlineData("Paid", true)]
    [InlineData("Draft", false)]            // ยังไม่ลง JE — แก้ในฟอร์มได้ตรง ๆ
    [InlineData("Voided", false)]
    public void Reclassify_line_only_after_the_je_exists(string status, bool expected)
    {
        var posted = new[] { "Approved", "Sent", "PartiallyPaid", "Paid" };
        Assert.Equal(expected, posted.Contains(status));
    }
}
