using Accounting.Models.Enums;

namespace Accounting.Models.DTOs.Accounting;

// ===== Chart of Accounts =====
public record CreateAccountRequest(
    string AccountCode,
    string AccountName,
    string? AccountNameEn,
    AccountType AccountType,
    Guid? ParentAccountId,
    string? Description);

public record UpdateAccountRequest(
    string? AccountName,
    string? AccountNameEn,
    string? Description,
    bool? IsActive);

public record AccountResponse(
    Guid Id,
    string AccountCode,
    string AccountName,
    string? AccountNameEn,
    AccountType AccountType,
    int AccountTypeValue,
    Guid? ParentAccountId,
    int Level,
    bool IsActive,
    bool IsSystemAccount,
    string? Description);

// ===== Journal Entry =====
public record CreateJournalEntryRequest(
    DateTime EntryDate,
    string? Description,
    string? Reference,
    List<JournalLineRequest> Lines,
    JournalType JournalType = JournalType.General,
    Guid? ProjectId = null,
    Guid? BranchId = null,
    Guid? DimensionId = null,
    string? Note = null,
    string? Tags = null,
    Guid? SourceDocumentId = null,           // ลิงก์ไปยัง Document ในระบบ (optional)
    string? SourceDocumentNumber = null,     // เลขเอกสารต้นทาง (resolve อัตโนมัติเมื่อให้ Id)
    bool ReplaceExistingForSource = false);  // ถ้า true: void รายการเดิมที่ link กับ source doc นี้ก่อนสร้างใหม่ (สำหรับ re-sync)

public record JournalLineRequest(
    Guid AccountId,
    decimal DebitAmount,
    decimal CreditAmount,
    string? Description,
    Guid? ProjectId = null,
    Guid? BranchId = null,
    Guid? DimensionId = null,
    string? Tags = null);

public record UpdateJournalEntryRequest(
    DateTime? EntryDate,
    string? Description,
    string? Reference,
    List<JournalLineRequest>? Lines,
    JournalType? JournalType = null,
    Guid? ProjectId = null,
    Guid? BranchId = null,
    Guid? DimensionId = null,
    string? Note = null,
    string? Tags = null,
    Guid? SourceDocumentId = null,
    string? SourceDocumentNumber = null);

public record JournalEntryResponse(
    Guid Id,
    string EntryNumber,
    DateTime EntryDate,
    JournalType JournalType,
    string? Description,
    string? Reference,
    JournalEntryStatus Status,
    bool IsAutoGenerated,
    decimal TotalDebit,
    decimal TotalCredit,
    List<JournalLineResponse> Lines,
    DateTime CreatedAt,
    Guid? ReversedByEntryId = null,
    Guid? OriginalEntryId = null,
    Guid? ProjectId = null,
    string? ProjectName = null,
    Guid? BranchId = null,
    Guid? DimensionId = null,
    string? Note = null,
    string? Tags = null,
    Guid? SourceDocumentId = null,
    string? SourceDocumentNumber = null,
    string? SourceDocumentType = null);

public record BatchVoidRequest(List<Guid> EntryIds);

public record ReverseJournalEntryRequest(
    DateTime? ReversalDate,
    string? Description);

public record CorrectJournalEntryResponse(
    JournalEntryResponse ReversalEntry,
    JournalEntryResponse DraftEntry);

public record JournalLineResponse(
    Guid Id,
    Guid AccountId,
    string AccountCode,
    string AccountName,
    decimal DebitAmount,
    decimal CreditAmount,
    string? Description,
    int LineOrder,
    Guid? ProjectId = null,
    string? ProjectName = null,
    Guid? BranchId = null,
    Guid? DimensionId = null,
    string? Tags = null);

// ===== Reports =====
public record TrialBalanceRequest(
    DateTime AsOfDate);

public record TrialBalanceResponse(
    DateTime AsOfDate,
    List<TrialBalanceItem> Items,
    decimal TotalDebit,
    decimal TotalCredit);

public record TrialBalanceItem(
    string AccountCode,
    string AccountName,
    AccountType AccountType,
    int AccountTypeValue,
    decimal DebitBalance,
    decimal CreditBalance);

public record BalanceSheetResponse(
    DateTime AsOfDate,
    List<BalanceSheetSection> Assets,
    List<BalanceSheetSection> Liabilities,
    List<BalanceSheetSection> Equity,
    decimal TotalAssets,
    decimal TotalLiabilities,
    decimal TotalEquity);

public record BalanceSheetSection(
    string AccountCode,
    string AccountName,
    decimal Amount,
    List<BalanceSheetSection>? Children);

public record ProfitAndLossResponse(
    DateTime FromDate,
    DateTime ToDate,
    List<PnlSection> Revenue,
    List<PnlSection> Expenses,
    decimal TotalRevenue,
    decimal TotalExpenses,
    decimal NetIncome);

public record PnlSection(
    string AccountCode,
    string AccountName,
    decimal Amount);

// ===== General Ledger =====
public record GeneralLedgerResponse(
    List<GeneralLedgerAccount> Accounts,
    DateTime FromDate,
    DateTime ToDate);

public record GeneralLedgerAccount(
    Guid AccountId,
    string AccountCode,
    string AccountName,
    AccountType AccountType,
    int AccountTypeValue,
    decimal OpeningBalance,
    decimal TotalDebit,
    decimal TotalCredit,
    decimal ClosingBalance,
    List<GeneralLedgerTransaction> Transactions);

public record GeneralLedgerTransaction(
    Guid JournalEntryId,
    string EntryNumber,
    DateTime EntryDate,
    JournalType JournalType,
    string? Description,
    decimal DebitAmount,
    decimal CreditAmount,
    decimal RunningBalance);

// ===== Fiscal Period =====
public record CreateFiscalPeriodRequest(
    int Year,
    int Month,
    DateTime StartDate,
    DateTime EndDate);

public record FiscalPeriodResponse(
    Guid Id,
    string Name,
    int Year,
    int Month,
    DateTime StartDate,
    DateTime EndDate,
    FiscalPeriodStatus Status);
