using Accounting.Data;
using Accounting.Models.Entities;
using Accounting.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace Accounting.Services.Implementations.Journal;

/// <summary>Fluent builder สำหรับสร้าง JournalEntry แบบ uniform ทั้งระบบ.
/// duplicate audit #4: เดิม DocumentService.AutoPostToJournalAsync +
/// PosService.CreateSalesJournalEntryAsync + CMS + Payroll ต่างคนต่างสร้าง JE
/// ด้วย field defaults ต่างกัน → fallback chain ของ account resolution drift
///
/// Builder ให้:
/// - Set header field มาตรฐาน (CompanyId, EntryNumber, FiscalPeriodId,
///   Status=Posted, IsAutoGenerated, SourceDocumentId)
/// - Add Dr/Cr line แบบ chained (.Debit(acct, amt, desc) .Credit(...))
/// - Auto balance check ก่อน save → throw ถ้า Dr ≠ Cr ภายใน 0.01
/// - Resolve EntryNumber ผ่าน GetNextJournalEntryNumberAsync (no race)
/// - Resolve FiscalPeriod ตาม EntryDate
///
/// Caller: `var je = await JournalEntryBuilder.For(db, companyId, date)
///   .Reference(docNumber).Description("...")
///   .Debit(cashId, 1000, "เงินสดรับ")
///   .Credit(revId, 935, "ขาย")
///   .Credit(vatId, 65, "VAT")
///   .PostAsync(actor);`
///
/// Phase 1: helper only — old paths continue. Phase 2: migrate AutoPostToJournal
/// + PosService.CreateSalesJE + CMS + Payroll.</summary>
public class JournalEntryBuilder
{
    private readonly AccountingDbContext _db;
    private readonly Guid _companyId;
    private readonly DateTime _entryDate;
    private readonly JournalEntry _je;
    private int _lineNo = 1;

    private JournalEntryBuilder(AccountingDbContext db, Guid companyId, DateTime entryDate)
    {
        _db = db;
        _companyId = companyId;
        _entryDate = entryDate;
        _je = new JournalEntry
        {
            CompanyId = companyId,
            EntryDate = entryDate,
            JournalType = JournalType.General,
            Status = JournalEntryStatus.Posted,
            IsAutoGenerated = true,
        };
    }

    public static JournalEntryBuilder For(AccountingDbContext db, Guid companyId, DateTime entryDate)
        => new(db, companyId, entryDate);

    public JournalEntryBuilder Type(JournalType type) { _je.JournalType = type; return this; }
    public JournalEntryBuilder Description(string desc) { _je.Description = desc; return this; }
    public JournalEntryBuilder Reference(string? reference) { _je.Reference = reference; return this; }
    public JournalEntryBuilder SourceDocument(Guid? docId) { _je.SourceDocumentId = docId; return this; }
    public JournalEntryBuilder Project(Guid? projectId) { _je.ProjectId = projectId; return this; }
    public JournalEntryBuilder CreatedBy(string actor) { _je.CreatedBy = actor; return this; }

    public JournalEntryBuilder Debit(Guid accountId, decimal amount, string? desc = null)
    {
        if (amount <= 0) return this;
        _je.Lines.Add(new JournalEntryLine
        {
            AccountId = accountId, DebitAmount = amount, CreditAmount = 0m,
            Description = desc, LineOrder = _lineNo++,
        });
        return this;
    }

    public JournalEntryBuilder Credit(Guid accountId, decimal amount, string? desc = null)
    {
        if (amount <= 0) return this;
        _je.Lines.Add(new JournalEntryLine
        {
            AccountId = accountId, DebitAmount = 0m, CreditAmount = amount,
            Description = desc, LineOrder = _lineNo++,
        });
        return this;
    }

    /// <summary>Persist JE: assign EntryNumber + FiscalPeriod + verify balance
    /// + add to DbSet. ไม่เรียก SaveChanges (caller รับผิดชอบเพื่อจะ batch
    /// หลาย op ใน 1 transaction ได้).</summary>
    public async Task<JournalEntry> PostAsync(string? actor = null, CancellationToken ct = default)
    {
        if (actor != null) _je.CreatedBy = actor;

        _je.TotalDebit = _je.Lines.Sum(l => l.DebitAmount);
        _je.TotalCredit = _je.Lines.Sum(l => l.CreditAmount);
        if (Math.Abs(_je.TotalDebit - _je.TotalCredit) > 0.01m)
            throw new InvalidOperationException(
                $"JE ไม่สมดุล: Dr {_je.TotalDebit:N2} ≠ Cr {_je.TotalCredit:N2} (Reference: {_je.Reference})");

        if (_je.Lines.Count < 2)
            throw new InvalidOperationException("JE ต้องมีอย่างน้อย 2 บรรทัด (Dr + Cr)");

        // Resolve EntryNumber (advisory-lock per prefix ภายใน)
        if (string.IsNullOrEmpty(_je.EntryNumber))
            _je.EntryNumber = await NextJournalNumberAsync(_db, _companyId,
                _je.JournalType == JournalType.General ? "JV" : "JE", _entryDate, ct);

        // FiscalPeriod auto-resolve
        var period = await _db.FiscalPeriods.AsNoTracking()
            .FirstOrDefaultAsync(f => f.CompanyId == _companyId
                && f.StartDate <= _entryDate && f.EndDate >= _entryDate, ct);
        if (period != null && period.Status != FiscalPeriodStatus.Open)
            throw new InvalidOperationException(
                $"งวด {period.Name} ถูกปิด — เปิดงวดก่อนจึงจะ post JE ได้ (EntryDate: {_entryDate:yyyy-MM-dd})");
        _je.FiscalPeriodId = period?.Id;

        _db.JournalEntries.Add(_je);
        return _je;
    }

    /// <summary>Static utility — ใช้ใน path ที่ยังไม่ migrate ไป builder.
    /// Advisory-lock per (companyId, prefix) ทำให้ N caller พร้อมกันยังได้
    /// เลขไม่ชนกัน.</summary>
    public static async Task<string> NextJournalNumberAsync(AccountingDbContext db,
        Guid companyId, string prefix, DateTime when, CancellationToken ct = default)
    {
        var yearMonth = when.ToString("yyyyMM");
        var jePrefix = $"{prefix}-{yearMonth}-";

        // ⚠️ ล็อกต้องคิดจาก **prefix เต็มรวมเดือน** และต้องเป็นค่าเดียวกันทุกผู้ออกเลข
        // เดิมมีผู้ออกเลขลง number space เดียวกัน 4 ตัว ด้วยคีย์ล็อก 3 แบบ:
        //   • ตัวนี้: HashCode.Combine(companyId, prefix, "je-seq")
        //   • FinancialManagementService: HashCode.Combine(companyId, "JV", ym)
        //   • AccountingService: Math.Abs($"je_number_{companyId}_{pattern}".GetHashCode())
        //     ← `string.GetHashCode()` ใน .NET Core **randomize ต่อ process**
        //       ⇒ สอง instance ได้คีย์คนละค่า = ล็อกนี้กันข้ามเครื่องไม่ได้เลย
        //   • EclAllowanceJob: **ไม่มีล็อก**
        // ⇒ approve เอกสาร (คีย์ A) พร้อมกับ post JE ค่าเสื่อม/ปันส่วน (คีย์ B)
        //   ไม่บล็อกกัน → อ่าน max ได้เลขเดียวกัน → ชน unique (CompanyId,
        //   EntryNumber) → "อนุมัติไม่สำเร็จ" แบบสุ่มที่กดใหม่แล้วหาย
        var lockKey = JournalNumberLockKey(companyId, jePrefix);
        await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock({0})", lockKey);

        var suffixes = await db.JournalEntries.IgnoreQueryFilters()
            .Where(j => j.CompanyId == companyId && j.EntryNumber.StartsWith(jePrefix))
            .OrderByDescending(j => j.CreatedAt)
            .Take(2000)
            .Select(j => j.EntryNumber.Substring(jePrefix.Length))
            .ToListAsync(ct);
        var nextSeq = 1;
        foreach (var s in suffixes)
            if (int.TryParse(s, out var parsed) && parsed >= nextSeq) nextSeq = parsed + 1;

        // นับ JE ที่ Add ค้างใน change tracker ด้วย — ยกมาจาก
        // AccountingService.GetNextEntryNumberAsync ซึ่งเป็นตัวเดียวที่เคยมี
        // (เคสจริง: อนุมัติใบกำกับแปลงจากใบแจ้งหนี้ → supersede reverse ใบเดิม
        // ทั้งคู่ prefix เดียวกันเดือนเดียวกัน · query DB ไม่เห็นใบที่ยังไม่ save
        // ⇒ เลขซ้ำ ⇒ unique index ล้มตอน SaveChanges = อนุมัติไม่ได้)
        var localMax = db.JournalEntries.Local
            .Where(j => j.CompanyId == companyId
                        && j.EntryNumber != null && j.EntryNumber.StartsWith(jePrefix)
                        && int.TryParse(j.EntryNumber[jePrefix.Length..], out _))
            .Select(j => int.Parse(j.EntryNumber[jePrefix.Length..]))
            .DefaultIfEmpty(0)
            .Max();
        if (localMax >= nextSeq) nextSeq = localMax + 1;

        return nextSeq <= 9999 ? $"{jePrefix}{nextSeq:D4}" : $"{jePrefix}{nextSeq:D5}";
    }

    /// <summary>
    /// คีย์ advisory lock ของ number space เลข JE — <b>ผู้ออกเลขทุกตัวต้องใช้ตัวนี้</b>
    ///
    /// <para>คิดจาก prefix เต็มที่รวมเดือนแล้ว (เช่น <c>"JV-202608-"</c>) เพื่อให้
    /// เดือนต่างกันไม่ต้องรอกัน แต่เดือนเดียวกันจาก**คนละ service** ต้องรอกัน.
    /// ห้ามใช้ <c>string.GetHashCode()</c> — .NET Core randomize ต่อ process
    /// ⇒ ค่าคีย์ต่างกันทุกครั้งที่รีสตาร์ต ล็อกจึงไม่กันอะไรเลยข้าม instance</para>
    /// </summary>
    public static long JournalNumberLockKey(Guid companyId, string fullPrefix)
        => Accounting.Helpers.AdvisoryLockKey.For(
            companyId, Accounting.Helpers.AdvisoryLockKey.JournalSequence, fullPrefix);
}
